### ISSUE TITLE
Facebook meta graphs not working 

### ISSUE THREAD

**Issue by outboxvision** [kni-labs/rrssb#101]
Great plugin!

I've added the facebook meta tags as in your example but it still gets random content from the page especially on the image thumbnail part:

Here's how the head code looks like: 
```
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Likeable - Imaginea ta suntem noi.</title>
  <meta name="description" content="text text text">
  <meta name="viewport" content="width=device-width, initial-scale=1">
   <!-- Facebook Open Graph Meta Tags -->
   <meta property="og:title" content="Likeable - Imaginea ta suntem noi." />
   <meta property="og:type" content="website" />
   <meta property="og:url" content="http://likeable.ro" />
   <meta property="og:image" content="http://website.co/img/logo.png" />
```
I'm more interested in the image part, why it doesn't retrieve the image I've specified? 
Any idea how can I force to retrieve the image I want? 
Thank you!

**Comment by dbox** [comment]
Can you post a link to your page or a second page?

**Comment by outboxvision** [comment]
Sure, here it is: http://likeable.ro

**Comment by dbox** [comment]
looks like you got it
