### ISSUE TITLE
Handling SVG not supported

### ISSUE THREAD

**Issue by AdamPS** [kni-labs/rrssb#102]
SVG is not supported in approx %5 of browsers (http://caniuse.com/#feat=svg).  Do you have any ideas for providing a fallback?  Thanks.

**Comment by dbox** [comment]
You could always [serve pngs as the fallback](https://css-tricks.com/svg-fallbacks/), but svg support was a requirement for this project since the beginning. [We](http://www.kurtnoble.com) haven't supported ie8 in years, and I really don't want to add the bloat for this.

**Comment by AdamPS** [comment]
Nice portfolio on your website!  I agree IE8 is low priority, but would prefer to degrade gracefully where possible.  At the moment it seems fairly messy and not very easy to use.

On my test server I have it roughly working as follows:
- Detect SVG support with javascript adapted from Modernizr and if not set a class on <html>
- If no SVG: disable responsive scripts (hiding the text is not helping if there is no image!)
- If no SVG, use CSS to collapse space of icon and ensure button width matches text width (buttons may wrap to multiple lines, but still looks OK and usable).
- Also I have adapted the base CSS to work better if scripts are disabled: again button width matches text, similar code to previous bullet.

I'm quite happy keeping these as my private modifications and closing the issue.  However if you have any interest in integrating them, let me know.  NB I have had to alter the approach in the CSS (more inline rather than floats and absolute) and it's currently less responsive (my deliberate choice), so I don't have code that would do the job without a bit more work.

**Comment by dbox** [comment]
Thanks @AdamPS. I'd be happy to look at what you've done just from a curiosity standpoint.

Also, have you looked at the stats specifically on the site(s) you're thinking of deploying RRSSB? I'd be curious to see those ie8 numbers. Every site we've ever deployed has WAY lower percentage on ie8 (basically nonexistent) than those worldwide numbers.

**Comment by connorwyatt** [comment]
@AdamPS If you really want to support PNG fallbacks then I recommend you try [SVGInjector](https://github.com/iconic/SVGInjector).

You will need to create the PNG versions yourself, and then you can use the SVG injector to inject the SVG then use a conditional (using Modernizr) on the PNG fallback.

**Comment by dbox** [comment]
@AdamPS Going to close this one. I looked at a lot of our analytics and the numbers were way less than 1%. Not really sure where the 5% figure is coming from.

Thanks!

**Comment by connorwyatt** [comment]
Good call

**Comment by AdamPS** [comment]
OK, thanks for the analysis.  I guess I had been believing the numbers on caniuse without actually doing my own checking!

I'd been testing my own site through old browsers quite a lot whilst doing the development so my own numbers were no skewed.
