### ISSUE TITLE
gulp doesn't update rrssb.min.js

### ISSUE THREAD

**Issue by fabean** [kni-labs/rrssb#104]
If I make changes in the js and run gulp, or let gulp run on watch it doesn't actually re-minify my js changes.

To test I completely emptied by rrssb.js and saved it.
![screenshot 2015-05-20 10 48 29](https://cloud.githubusercontent.com/assets/3298524/7730088/df41ad1e-fedd-11e4-94fd-b81d866d4920.png)

I ran gulp
![screenshot 2015-05-20 10 48 55](https://cloud.githubusercontent.com/assets/3298524/7730089/df41ca60-fedd-11e4-9d62-f2caf4986a62.png)

Check then min.js and there have been no changes.
![screenshot 2015-05-20 10 48 35](https://cloud.githubusercontent.com/assets/3298524/7730087/df3eb08c-fedd-11e4-81ce-46a6d3c35712.png)

I'm not a gulp man but a grunt man so without looking into this too far I'm not exactly what the issue is. I do see on watch for js is `gulp.watch("*.js").on('change', browserSync.reload);` so there it's not even trying to run uglify.

**Comment by dbox** [comment]
paging @connorwyatt

**Comment by connorwyatt** [comment]
Okay, I'll have a look at it now, will get back to you when I find out what's going on :)

**Comment by connorwyatt** [comment]
Can see the problem, it was a foresight on my part, correcting it now

**Comment by dbox** [comment]
Awesome! Thanks @connorwyatt! 

@fabean I can't test it right now. Could you pull down `dev` branch and make sure that fixes your issue?

**Comment by connorwyatt** [comment]
@dbox You're welcome :)

**Comment by dbox** [comment]
@connorwyatt SO FAST

**Comment by connorwyatt** [comment]
@dbox Haha caught me at a good time :)

**Comment by fabean** [comment]
So still didn't work for me, maybe I'm just crazy?

I did up doing this copying what was happening for imagemin and it started working for me.

```
gulp.task('uglify', function() {
  gulp.src(['js/rrssb.js'])
  .pipe(uglify())
  .on('error', util.log)
  .pipe(rename({
    extname: '.min.js'
  }))
  .pipe(gulp.dest('js'));
});
```

**Comment by connorwyatt** [comment]
Try checking out the dev branch and see if it works, it's not currently in the master

**Comment by dbox** [comment]
Yeah, if you can confirm working on `dev` branch @fabean I'll merge them site unseen. :)

**Comment by fabean** [comment]
I am on dev branch. I see the changes made help with the actual watch `gulp.watch(["js/*.js", "**/*.min.js"], ['uglify']);` but I'm thinking the issue is with the uglify task itself.

Here are the changes I made to the gulpfile.
![screenshot 2015-05-20 13 47 29](https://cloud.githubusercontent.com/assets/3298524/7733748/caefeac4-fef6-11e4-89c5-27f3b0eec55f.png)

I add a console.log to the bottom of the javascript.
![screenshot 2015-05-20 13 47 16](https://cloud.githubusercontent.com/assets/3298524/7733747/cae42b44-fef6-11e4-826c-3f712b63a8ba.png)

and the changes brought over to the minimized version.
![screenshot 2015-05-20 13 47 21](https://cloud.githubusercontent.com/assets/3298524/7733746/cae39fb2-fef6-11e4-9fd9-ca4b44d9cde7.png)

**Comment by connorwyatt** [comment]
Yeah I have the same issue, I'm about to go out and then I'll rewrite it.

It is sometimes working and sometimes not, so I'll sort it.

Apologies

**Comment by dbox** [comment]
:beers: :computer:

**Comment by fabean** [comment]
No worries, I'm happy with the fast responses! And I already minified it myself hours ago so it's not like I'm waiting on a bug fix to continue working.

**Comment by connorwyatt** [comment]
That's good, should have it fixed within the hour

**Comment by connorwyatt** [comment]
Such a silly mistake. I didn't even call uglify on the js file...

I don't know why it was working for me at one point though?

Once I get home I'll add it in.

**Comment by dbox** [comment]
Thanks @connorwyatt . @fabean Can you confirm this working? and I'll get it into `master`

**Comment by connorwyatt** [comment]
@dbox You're welcome, I'll try and get it into one command again soon so that you can just run gulp instead of needing to run gulp watch as well

**Comment by dbox** [comment]
love it. thanks

**Comment by fabean** [comment]
Works for me if I run `gulp watch`

**Comment by dbox** [comment]
All good? Gunna close and push into master

**Comment by fabean** [comment]
Yes, works for me off first run and off watch. Thanks @connorwyatt & @dbox

**Comment by connorwyatt** [comment]
@fabean Glad I could be of help.

@dbox I think it's ready to go :+1: :)

**Comment by connorwyatt** [comment]
@dbox Would you be able to merge the new dev branch changes into the 2.0 branch and I'll take a look at adding a count?

**Comment by dbox** [comment]
Should be good to go.

**Comment by connorwyatt** [comment]
Awesome thanks
