### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by dbox** [kni-labs/rrssb#112]
Is npm install something people would like to see?

**Comment by connorwyatt** [comment]
Personally I only use npm for dev tools like gulp and then bower for any front end dependencies. I think a lot of people use it that way and it might not get used, I personally wouldn't unless you get mass demand :)

**Comment by Ardakilic** [comment]
I'd love to see a npm install for this!

**Comment by connorwyatt** [comment]
@dbox If you want it in the v2 I can add it in, let me know

**Comment by dbox** [comment]
Might be cool. I'd be into checking it out just to learn more about how it
works.

**Comment by connorwyatt** [comment]
Fair enough I'll leave that to you

**Comment by dbox** [comment]
Haha. No I meant feel free to add to your list. I'll check what you do.

**Comment by connorwyatt** [comment]
To be honest I've never done it before but I'll give it a go if you don't
want to

**Comment by dbox** [comment]
Let's put as lowest priority for now over new 2.0 improvements.

**Comment by connorwyatt** [comment]
+1

**Comment by dbox** [comment]
This will happen with 2.0
