### ISSUE TITLE
"Moderately responsive SSB"

### ISSUE THREAD

**Issue by AdamPS** [kni-labs/rrssb#116]
I realise it may seem counter-intuitive based on the name of the library, but I would be interested in options for less responsiveness.  Why do I not just go to a less-responsive library?  Well you guys have some of the most attractive and lightweight buttons I've been able to find.  Also I'd like to use one library everywhere, whether I need responsive or not.

* Personally I'm not so keen on having the buttons shrink one-by-one and would prefer an option for all-or-nothing.
* Often it's clear to the site-designer the approx size of button that fits the design, so perhaps may prefer to lock it in as small or micro or large of whatever.  Also may prefer to lock in text on or off.
* The current script can be a bit slow.  Page load is slower on older mobiles.  Resizing a window totally fails to be smooth on my decent speed PC whereas it is fine without the script.  It would be great if the less responsive option could also lead to it running faster.
* In the extreme case, the script isn't actually needed at all!  I have a site where I have turned it off.  I still get the benefit of lovely minimal buttons.  I added a media query to hide the text on small screens.

Thanks!

**Comment by connorwyatt** [comment]
This would be a separate project I think but I might be willing to take it
on in a week or so. If you have more ideas, add them in here

**Comment by AdamPS** [comment]
Great, thanks!

**Comment by dbox** [comment]
You could achieve this right now by just setting fixed size container around `.rrssb-buttons`. (Then setting fixed sizes at certain breakpoints.)

But, yes, a little off-project. :)

**Comment by dbox** [comment]
Super lightweight thing might be great. Feel free to fork and go for it! Closing this out for now.

**Comment by dbox** [comment]
I might even take it on post 2.0 myself.

**Comment by AdamPS** [comment]
I have made some progress, but not fully working.  I'll try and get something I can share soon.
