### ISSUE TITLE
Wordpress link in Readme.md goes nowhere!

### ISSUE THREAD

**Issue by dillonbailey** [kni-labs/rrssb#120]
Yo!

Love your work, just wanted to let you know the wordpress plugin link looks either broken or like the plugin has been taken down.

DB

**Comment by dbox** [comment]
Thanks @dillonbailey . The Wordpress plugin is managed by @alan-reed. Read more here: https://github.com/kni-labs/rrssb/issues/93

**Comment by dillonbailey** [comment]
Ah, yep, cool thanks @dbox !
