### ISSUE TITLE
Facebook share cancel button don't work

### ISSUE THREAD

**Issue by mikiand** [kni-labs/rrssb#127]
i have a problem with Facebook share cancel button, suddenly it stopped working

**Comment by dbox** [comment]
Can you post a link?

**Comment by mikiand** [comment]
there is no concrete link i think this problem is on all pages that are using rrssb, see here on the official demo page http://kurtnoble.com/labs/rrssb/ click on the faceook button than when the popup opens click cancel, the popup will not close itself. This is happening on chrome, mozilla also, it works on internet explorer.

**Comment by dbox** [comment]
That's handled on Facebook's side, however it's working as expected for me on OSX Safari, Chrome, & Firefox ....
