### ISSUE TITLE
Single button less than 200px becomes "tiny-format"

### ISSUE THREAD

**Issue by jsmoriss** [kni-labs/rrssb#128]
I've been working on some CSS to align the buttons vertically by putting each button in it's own container. If the container for a single button is less than 200px wide, RRSSB formats it as "tiny".

Here's my temporary patch:

````
$ diff ~/svn/github/jsmoriss/rrssb/trunk/js/rrssb.js rrssb.js
135c135
< 			if (containerWidth < 200) {
---
> 			if ( containerWidth < $('li', self).length * 25 ) {
````

js.

**Comment by jsmoriss** [comment]
Actually, I think this may be better. ;-)

````
$ diff ~/svn/github/jsmoriss/rrssb/trunk/js/rrssb.js rrssb.js
126a127
> 			var buttonCountSmall = $('li.small', self).length;
129c130
< 			if (buttonWidth > 170 && $('li.small', self).length < 1) {
---
> 			if (buttonWidth > 170 && buttonCountSmall < 1) {
135c136
< 			if (containerWidth < 200) {
---
> 			if ( containerWidth < buttonCountSmall * 20 ) {
````

js.

**Comment by dbox** [comment]
Mind pasting a screenshot of what you're doing?

**Comment by jsmoriss** [comment]
Without that change, any single button within a UL of 199px wide or less would turn into a tiny button. Obviously, a tiny button of 199px wide is a bit of a problem. ;-) With this change, the width must be less than "number of small buttons, multiplied by 20" pixels wide. So, if you have 10 buttons, they turn tiny when the container is 200px or less. If you have 1 button, the container must be 20px or less.

As an example, to create a floating sidebar like this, each button is in its own UL of 40px:

http://www.awesomescreenshot.com/088523cvde

js.

**Comment by dbox** [comment]
Gotcha. Yes. I have a note about this in 2.0. Thanks!!

**Comment by jsmoriss** [comment]
No problem.

BTW, there will soon be an RRSSB plugin available for WordPress as an extension to WPSSO. WPSSO is a social optimization plugin that can provide the RRSSB buttons with correct URLs, titles, descriptions, images, etc. I should have it done in another week or so...

js.

**Comment by dbox** [comment]
@jsmoriss Great! We're trying to get 2.0 out the door as well here, so don't know if that will be helpful or not for you.

We just need to port the resizing functions over from 1.x to 2.0 and it should be pretty ready to go. It's a much nicer setup..

**Comment by jsmoriss** [comment]
FYI - I just released WPSSO RRSSB - an RRSSB plugin for WordPress. ;-)

https://wordpress.org/plugins/wpsso-rrssb/

js.

**Comment by dbox** [comment]
Nice! There will be a lot of happy people.

Maybe a little credit to this repo on the homepage would be nice :wink:

**Comment by jsmoriss** [comment]
I was just thinking that - I was pushing to get this plugin out today and need to fill-out some of the details, like credit for the RRSSB css/js stuff. ;-)

js.

**Comment by dbox** [comment]
Cool. I'll get in in the readme soon.

**Comment by dbox** [comment]
Happy to accept a pull request if you have this fixed.

**Comment by jsmoriss** [comment]
Done. ;-)

js.

**Comment by dbox** [comment]
Great. Looking now. Thanks!

**Comment by Marc-pi** [comment]
@dbox, don't forget to update changelog/readme ;-)
great anyway

**Comment by dbox** [comment]
@Marc-pi which part?

**Comment by Marc-pi** [comment]
readme.md we are sticked to 1.8.0 ;-)

**Comment by dbox** [comment]
Ah yeah. Thanks. I think I"m just going to remove that entirely. It's all available under releases tab:

https://github.com/kni-labs/rrssb/releases

**Comment by Marc-pi** [comment]
yes, i use that page also, but i noticed that in package when reading the readme and other files
