### ISSUE TITLE
buttons look very small when first loaded in a modal window

### ISSUE THREAD

**Issue by aastrong** [kni-labs/rrssb#13]
I've got an issue where i've added the RRSSB inside a modal window. 
The buttons seem to load very very small when the modal first opens, but the minute i resize the screen, it works perfectly. 

I've attached a screenshot
![issue](https://f.cloud.github.com/assets/2792103/2276330/100d4cd0-9f32-11e3-8a72-870b72b1821d.jpg)

**Comment by caleuanhopkins** [comment]
Can we have this solution in a "tips & tricks" section or in the readme? Took my ages to find this and it's an elegant solution.

**Comment by dbox** [comment]
Sure. Mind doing a pull request?
