### ISSUE TITLE
Tidy up SVG files

### ISSUE THREAD

**Issue by AdamPS** [kni-labs/rrssb#130]
As far as I can tell the SVG icons can be optimised in various ways to remove some unneeded lines and tidy up.
* Use square viewport (pocket) else the icon ends up slightly larger than all the others
* Don't need width, height - set in CSS/JS
* Don't need fill="#FFF" - set in CSS
* Don't need preserveAspectRatio, class, fill-rule - only present on one or two icons and doesn't seem to have any effect.
* For consistency, put viewport attribute after xmlns

Pull request coming up.  I'm new to git/git-hub, so sorry if I didn't do it right.

**Comment by dbox** [comment]
Thanks Adam..

Would you mind doing a pull request into 2.0 branch for this?

Also if you're looking for more places to help out, we have a lot of 2.0 ready to go, we just need port the resizing functions from 1.x over.

Ideally I'd like to keep all new additions in the 2.0 branch. Thanks!

**Comment by AdamPS** [comment]
OK, I can do it for 2.0.  But README.md says to do dev :-)  (It also has broken links for the dropbox screenshots list in the support section.)

I'll reply to your request for help on the v2.0 issue.

**Comment by AdamPS** [comment]
Oh by the way I didn't include index.html in my pull request.  Is that file generated automatically or do I need to do it by hand?

**Comment by dbox** [comment]
currently done by hand ... everything else is merged up if you'd like to pull down then submit a new index.

**Comment by AdamPS** [comment]
Thanks.  OK done for the index.
