### ISSUE TITLE
CSS for polygon no longer needed

### ISSUE THREAD

**Issue by AdamPS** [kni-labs/rrssb#132]
SVG have now been optimised to use path.  Can drop polygon, saves a couple of kB of CSS.

I could do a pull request, but let's wait for the outcome of the discussion of the future of different branches first.

**Comment by dbox** [comment]
Thanks! Go ahead and pull request to `dev` and I'll get it merged up. (Just getting a little hairy in this in-between time. Don't want to have to recreate a bunch of work in 2.0)

**Comment by dbox** [comment]
So even more optimizations since the last pull request?

**Comment by AdamPS** [comment]
I've now added this change to my other pull request.  I've just changed the SCSS so far.  I don't use the tools installed to regenerate the CSS from that.  I could do a simple search and replace by hand, or maybe you could rerun the regeneration process.
