### ISSUE TITLE
Missing index.html entry for instagram and delicious

### ISSUE THREAD

**Issue by AdamPS** [kni-labs/rrssb#134]
SVG and SCSS are fine.  In 2.0 branch, the equivalent is the js file which is also missing.

Basically the extra information needed is the URL.  It would help if someone who uses these services (not me sorry) could figure out what is needed and test.

**Comment by dbox** [comment]
you can't really "share" through Instagram so the link is just `http://instagram.com/username`

Delicious looks to be something like this now:
`https://delicious.com/save?v=5&noui&jump=close&url='http://urlhere'&title='title-here'`

However, not sure how many people are still using it...

**Comment by AdamPS** [comment]
delicious - I only mentioned it because we have the CSS and SVG.  I don't know how many people are using it.  I'm not fussed either way to have it fully or delete it fully (but best not to have it only partly).

Let me know and I can make a push request.

**Comment by AdamPS** [comment]
Although seeing as someone has gone to the trouble of creating delicious maybe we should just leave it.
