### ISSUE TITLE
Shouldn't ampersand not be encoded for email body?

### ISSUE THREAD

**Issue by ivanakimov** [kni-labs/rrssb#140]
I had an issue where email body would not show up (Chrome 45 on Mac); changing `&amp;` to `&` fixed it: https://github.com/kni-labs/rrssb/blob/master/js/rrssb.js#L65

In the example here they also use non-encoded ampersand: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Email_links

**Sidenote:** Also is `(settings.emailAddress !== undefined)` right above it really required? I omitted passing `emailAddress` at first and was wondering why the rest of my parameters were not showing up...

P.S: Thanks for the project! :+1:

**Comment by odbol** [comment]
Fixed by #151
