### ISSUE TITLE
CSS Glitch on tiny format - front end js app

### ISSUE THREAD

**Issue by newtonianb** [kni-labs/rrssb#143]
I'm trying to make this work inside my front end js app. 
When a view is rendered I manually call ``rrssbInit.init()``

I just modified the library and added this line ``window.rrssbInit = rrssbInit;``

I can't determine if my CSS glitch is due to this or natively in the library

![ff](https://cloud.githubusercontent.com/assets/2313644/10289962/5763ec3c-6b6f-11e5-815a-1239d0e5d665.jpg)

**Comment by dbox** [comment]
doesn't seem like something native to the library. Feel free to post an example.
