### ISSUE TITLE
Smallest icon size is shifted in IE11

### ISSUE THREAD

**Issue by rbu** [kni-labs/rrssb#144]
Steps to reproduce:
1. Open latest IE11
2. Go to http://kurtnoble.com/labs/rrssb/
3. Set window size as small as possible

![rrsb](https://cloud.githubusercontent.com/assets/65913/10455052/2be15e8c-71b9-11e5-9d13-9021a0577db7.gif)

**Comment by rbu** [comment]
The span containing the svg is missing a height declaration (thus has height: auto) and for some reason this means that the ul's height is not getting pushed all the way inside. As a workaround, this helps (and may be the solution?):
```
.tiny-format .rrssb-icon {
	height: 100%;
}

**Comment by dbox** [comment]
Good catch! Looking into this.

**Comment by dbox** [comment]
@rbu Want to try a PR for this?

**Comment by rbu** [comment]
Sure, sent one.
