### ISSUE TITLE
Strange rendering: difference between page load and resizing, bad labels, etc.

### ISSUE THREAD

**Issue by alejandroiglesias** [kni-labs/rrssb#156]
Hi, I'm trying to implement RRSSB on a website, but it renders quite strange. The thing that calls my attention the most is that it renders differently on page load and after resizing a few px. Seems that the window resize event calls another function that is not called on page load. Besides that, it looks quite different than the demo page, which is what I was expecting (all buttons on the same row and adapting to the width of the container). I loaded the CSS and JS files and put the HTML snippets on the page. I'm also using Bootstrap 3 for the layout.

On page load, before resizing.
![](https://cldup.com/v9EtyExZP8.png)

After resizing a few px:
![](https://cldup.com/Wqe_39vNia.png)

**Notice:**

* Weird behavior: initial render is quite different than after risizing.
* On page load, buttons are not on the same row.
* Label overflows button.
* No space between icon and label.

**Comment by dbox** [comment]
The JS isn't firing..

**Comment by alejandroiglesias** [comment]
@dbox thanks for replying. I've added a log on the `rrssbInit` function and it is being called.

**Comment by dbox** [comment]
Jquery?

**Comment by alejandroiglesias** [comment]
Using jQuery 2.1.4.

**Comment by dbox** [comment]
Can you post a stripped down version somewhere?

**Comment by alejandroiglesias** [comment]
Sure, [here](https://gist.github.com/alejandroiglesias/9ee111827c36f88c32ce) is a barebones version of my HTML file.

**Comment by dbox** [comment]
Going to have to see the full thing posted somewehre. Actually can you hop in here:

https://gitter.im/kni-labs/rrssb

Going to start a chat room for people who need help with implementation / questions. Thnx!

**Comment by alejandroiglesias** [comment]
@dbox just found out the issue, I was using an Angular `<ng-include>` tag for including the HTML template for the sharing buttons. Seems that it was loading it after the RRSSB JS. 
Thanks and sorry for any hassle.

**Comment by dbox** [comment]
Glad you figured it out! :tada:
