### ISSUE TITLE
Add Whatsapp icon

### ISSUE THREAD

**Issue by pascalwacker** [kni-labs/rrssb#162]
Hi

I really like your work and how nice it scales. The only thing, that is missing for me is a "Whatsapp" icon (which should only display on phones, so let's say when the resolution is <= 767px)

is there anything like that planed?
If no, could you tell me, how to make an path from an icon, to add it?

Thanks (:

**Comment by dbox** [comment]
dup of #81 and #122. I'm fine with adding but we can't simply just remove it with a media query, will break the setup. Open to thoughts on what to do with it

**Comment by pascalwacker** [comment]
What's about hiding it in the `$(window).resize(function () {` on line 359 of https://github.com/kni-labs/rrssb/blob/master/js/rrssb.js
You could add a class like `hidden` and then check for it in the `checkSize` function to ignore the "hidden" button.

Maybe it could be used as a general approach for hiding and showing buttons for desktop or mobile only.

**Comment by j3ll3nl** [comment]
With the button-code from #122 and the idea mentioned above this would be a great feature to have.

**Comment by pascalwacker** [comment]
Ouu, I haven't seen https://github.com/kni-labs/rrssb/issues/122 yet, but I also made an implementation and a pull request for it: https://github.com/kni-labs/rrssb/pull/166

**Comment by dbox** [comment]
Should be good to go in `1.10.0`. Let me know if any issues arise! :tada:
