### ISSUE TITLE
google+ example broken

### ISSUE THREAD

**Issue by kow** [kni-labs/rrssb#163]
the example links to:
https://plus.google.com/share?url=A%20snow%20report%20that%20gives%20Lodging%20Discounts%20when%20it%20snows!%20I%27ve%20just%20claimed%20mine%20at%20the%20Leavetown.com%2020cm%20Rule%20Snow%20Report%20page.%20If%20you%20ski%20or%20snowboard%2C%20check%20it%20out.%20http://kurtnoble.com/labs/rrssb/index.html

which gives error 400

should be:
https://plus.google.com/share?url=http://kurtnoble.com/labs/rrssb/index.html

**Comment by dbox** [comment]
Where are you seeing that?

**Comment by kow** [comment]
It was throwing the error when I submitted the bug, but seems to be ok today.
In any case, the documentation calls for the URL param to be a URL, and seems to throw away the text that precedes it on the example page.
https://developers.google.com/+/web/share/#sharelink
