### ISSUE TITLE
uBlock is blocking it

### ISSUE THREAD

**Issue by PabloC** [kni-labs/rrssb#164]
I'm using uBlock on Google Chrome, and it is blocking the script. Buttons are not appearing.

**Comment by dbox** [comment]
FWIW I've never heard of uBlock. Happy for someone to investigate, but not going to be something I can look into.

**Comment by PabloC** [comment]
2,758,242 users are using this adblock.

Apparently, there is a site https://forums.lanik.us/ that has all the URLs used in the plugin marked as blocked. 

Screenhost here:

https://www.dropbox.com/s/edynr9lcsgn71xo/Screen%20Shot%202016-01-22%20at%2017.34.31.png?dl=0

**Comment by dbox** [comment]
So it's blocking facebook's default social sharing url. Seems like a bad idea imho

**Comment by RyanRoberts** [comment]
Surely if a user of uBlock has chosen to block social sharing links, you should respect that…?

**Comment by dbox** [comment]
Is that not what's happening?

**Comment by PabloC** [comment]
uBlock is a nice adblocker. It's faster than adblock I don't know why they
are blocking this buttons, but it's the first time that I notice this.

**Comment by dbox** [comment]
Yeah, I'm afraid you'll have to take up any issues with them. We can't do anything about people blocking the common sharing urls.

**Comment by dbox** [comment]
Any follow up on this? Seems like its out of our control.

**Comment by theus** [comment]
I use uBlock too but here it's not blocking nothing. It's probably the filters... it has some filters that block social things and privacy tracking. I believe that some these should blocking the icons.

**Comment by dbox** [comment]
Gunna close this one. Happy to look at it if it's something we can change, but I don't think it is.
