### ISSUE TITLE
https://wordpress.org/plugins/ridiculously-responsive-social-sharing-buttons/ broken

### ISSUE THREAD

**Issue by jsmoriss** [kni-labs/rrssb#165]
FYI - You have a link to a WordPress plugin of RRSSB at https://wordpress.org/plugins/ridiculously-responsive-social-sharing-buttons/, but that plugin does not exist.

You may want to link these two instead:

https://wordpress.org/plugins/rrssb/
https://wordpress.org/plugins/wpsso-rrssb/

js.

**Comment by dbox** [comment]
Thanks. Want to make a pull request?
