### ISSUE TITLE
Buttons don't work in .php file

### ISSUE THREAD

**Issue by jasminejjj777** [kni-labs/rrssb#170]
Thank you for responsive social sharing buttons,they're awesome .
When i use these  social sharing buttons in .html file ,everything works well, BUT when i use the same code,the same href ,src  links  in .php  file,i get these error

1/Uncaught TypeError: $(...).rrssb is not a function

In  http://localhost/test/share/share.html  file some of the buttons are displayed ,some are not...

Here are the files
[test.zip](https://github.com/kni-labs/rrssb/files/132195/test.zip)

**Comment by dbox** [comment]
sounds like your js isn't being referenced. I dont really have a way to test the php..

**Comment by jasminejjj777** [comment]
I've checked the code,this is what i have in index.php (I've placed js files in jsShare folder)
`<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script>
    window.jQuery || document.write('<script src="jsShare/vendor/jquery.1.10.2.min.js"><\/script>')
  </script> 
  <script src="jsShare/rrssb.min.js"></script>`

I've downloaded  ZIP files from git-hub(rrssb-master) and tried to check it for php,this is what i have in index.html

![4](https://cloud.githubusercontent.com/assets/17268786/13212755/149170a8-d95d-11e5-9582-cad71535813c.png)

BUT,when i replace rrssb-master folder in htdocs and save index.html as index.php,this is what i have(some buttons are displayed,some-are not)

![5](https://cloud.githubusercontent.com/assets/17268786/13212793/7b631372-d95d-11e5-8290-6d245b2b13d9.png)
