### ISSUE TITLE
Mobile Unreadable

### ISSUE THREAD

**Issue by Number-1** [kni-labs/rrssb#172]
When I used the js in the download ("js/rrssb.min.js") everything looked OK on desktop but mobile was too small to read with more than 3 buttons. Strangely enough the [demo ](http://kurtnoble.com/labs/rrssb/)switches to icons on mobile so not an issue. 

Using the [build.js](http://kurtnoble.com/labs/rrssb/js/build.js) from [demo ](http://kurtnoble.com/labs/rrssb/) works fine. 

Not sure what the difference is since it's minimized. Love the buttons.

**Comment by dbox** [comment]
Can you post a stripped down example somewhere demonstrating what is going on?

**Comment by Number-1** [comment]
Sure - [example](http://downsconsultingservices.com/test/rr-tst.html)


Looks like the attached on the phone.  Looking at it on a desktop is deceptive. There's no room on a small screen for all that text.


![too small for phone](https://cloud.githubusercontent.com/assets/3686121/13203206/5cb14fec-d878-11e5-84de-637c9993d18b.png)

**Comment by dbox** [comment]
try adding this to your `head`:

`<meta name="viewport" content="width=device-width, initial-scale=1">`

**Comment by Number-1** [comment]
I would have sworn I tried that last night. Added and it works perfectly.

**Comment by dbox** [comment]
Whoo hoo! 🎉
