### ISSUE TITLE
Twitter share page error in IE11

### ISSUE THREAD

**Issue by coolwebs** [kni-labs/rrssb#179]
Have just tested RRSSB out on all the common browsers that we need to and noticed that there is an issue with IE11. When clicking on the Twitter button, the window appears OK, but as soon as a user goes to tweet the message - it goes to an error (403) page with the title "The website declined to show this webpage.   Most likely causes: - this website requires you to log in.

I can confirm that I am logged in to Twitter when testing. Can someone please check and confirm? It works in every other major browser.

**Comment by coolwebs** [comment]
Actually, after doing more testing I think this was all on my end. I think it was a conflict between encoding the data in the URL and using Twitter cards metadata (plus injecting data variables into the code which dynamically grab the URL and name of the page). I think if using Twitter card metadata, you only need to share the URL and not the other text but I can't find solid information to back this up right now.

**Comment by dbox** [comment]
👌 Post if anything else pops up
