### ISSUE TITLE
Rails integration link is offline!

### ISSUE THREAD

**Issue by Rynaro** [kni-labs/rrssb#182]
The Ruby on Rails integration documentation website url is offline. The url now redirects to an webpage showing that "URL is now available to purchase".
I think, its a good idea removing this topic from README

**Comment by dbox** [comment]
Hi @Rynaro. Thanks for the lookout. Want to make a PR for this?

**Comment by Rynaro** [comment]
The pull request is here. :smiley: 
I've removed the Rails link, and adjusted the link of CDN too.

**Comment by dbox** [comment]
Whoot! thnx.
