### ISSUE TITLE
Buttons on ajax content

### ISSUE THREAD

**Issue by xtianus** [kni-labs/rrssb#184]
I'd like to show the share buttons on an ajax-loaded modal.
The modal is of course loaded after rrssb has been initialized on the main page, so the buttons don't behave well. I tried calling rrssbInit() in the ajax modal but it's not enough. This is the result:

![image](https://cloud.githubusercontent.com/assets/7997535/17812091/e3a926ec-6625-11e6-836d-ae0410c1ba2f.png)

**Comment by dbox** [comment]
Can you provide a demo / [minimal working example](https://www.wikiwand.com/en/Minimal_Working_Example)?

**Comment by xtianus** [comment]
Can't give you a demo right now buy I can tell you what I did to make it work:

- removed "rrssbInit();" from end of "$(document).ready(function(){"
- changed "$(document).ready(function(){" into "var documentReady = function() {"
- added "documentReady();" just after "var rrssbInit = function() {"

Now I can call "rrssbInit();" whenever I need to initialize the buttons. For example after a bootstrap modal has opened:

```
		    	$('#ajaxModal').on('shown.bs.modal', function (e) {
			    	rrssbInit();
	    		});
```

**Comment by dbox** [comment]
Let me know if you can post a demo and we'll reopen.
