### ISSUE TITLE
Display issues on hidden div

### ISSUE THREAD

**Issue by travbus** [kni-labs/rrssb#185]
Weird display on a hidden div when it is called to appear  the first button is huge. Resize window and buttons are displayed normally.

**Comment by dbox** [comment]
Hi @travbus. You're going to have to give some more information for us to help out. Can you provide a demo / [minimal working example](https://www.wikiwand.com/en/Minimal_Working_Example)?

**Comment by spacedragn** [comment]
Hi – I'm experiencing something similar. It only happens when the window is resized while the tray is closed. When the tray is open, all of the buttons are unstyled and the first button icon is gigantic. http://demo.jamiesanchez.com/rrssb/
