### ISSUE TITLE
feature request: npm profile

### ISSUE THREAD

**Issue by cdaringe** [kni-labs/rrssb#194]
i commonly like to share my "work" profile with people, which is generally my npm packages, https://www.npmjs.com/~cdaringe

it would be great to get npm on here!

it could be nice too, to keep file sizes down, to modularize the core package sites for those of us who are doing our own builds.  then, the dist/ could be the big everything-goes-in-here package, as is the status quo.  just spit-ballin' here

**Comment by dbox** [comment]
Hey @cdaringe! RRRSSB is currently available vs npm: https://www.npmjs.com/package/rrssb/, however, like you stated we can do a lot to improve it, especially what gets delivered. v2 is set to do that but currently stalled out. Care to dive in and help?
