### ISSUE TITLE
Adblock is realy blocking rrssb-buttons entirely!

### ISSUE THREAD

**Issue by ballios** [kni-labs/rrssb#215]
Adblock (the most popular Chrome extension) is realy blocking rrssb-buttons entirely!
And what we have to do?

**Comment by dbox** [comment]
can you give some more information?

**Comment by ballios** [comment]
What information? ))
You can just install Adblock in your browser and will see that all buttons have disappeared...
What a pity that this can not be avoided!

**Comment by dbox** [comment]
More information meaning:
1. What adblocker are you using?
2. Can you produce a minimal working example?

Here's mine:

![screenshot 2018-04-02 15 29 51_preview](https://user-images.githubusercontent.com/296130/38214691-11569200-368b-11e8-976a-25750c346f9f.png)

**Comment by ballios** [comment]
Hmm...
Dear sir, you are very simple, I guess... ))
Most of people turn "Antisocial filter list" (removes social media buttons) on - in Filter List of Adblock that you show me on your screenshot.
Turn that filter on and... the miracle of disappearance.

**Comment by dbox** [comment]
> Most of people turn "Antisocial filter list" (removes social media buttons) on - in Filter List of Adblock 

Doesn't this answer your own question?

**Comment by dbox** [comment]
I'd also assume most people do NOT change default settings, but hard to know without some sort of stats on it.

**Comment by ballios** [comment]
Ok, leave it as is...
