### ISSUE TITLE
Sites Using RRSSB

### ISSUE THREAD

**Issue by dbox** [kni-labs/rrssb#39]
Business Insider:
http://www.businessinsider.com/share-of-iphone-ownership-in-the-us-2014-5#!HlFqK

Anyone else seen it around the web yet?

**Comment by rimkashox** [comment]
I'm using them with rails here: http://www.emergencynumbers.org

Here's a how to for rails:

In your Gemfile at the top you add:

source 'http://rails-assets.org'

And somewhere below:

gem 'rails-assets-RRSSB’

In application.js you add:

//= require RRSSB

And finally in application.css you add:

*= require RRSSB

Then your buttons will be working :-)
