### ISSUE TITLE
Namespace CSS Classes

### ISSUE THREAD

**Issue by aarreedd** [kni-labs/rrssb#42]
Some of the RRSSB wordpress plugin users are encountering problems when their theme or another plugin have a CSS class with the same name as one in the RRSSB plugin. For instance 'icon' is common and often causes conflict. If users have other social sharing buttons on their page then the classes 'facebook','twitter','linkdin', etc often conflict as well. If we prefix all of the classes with 'rrssb-' these problems would be resolved. 

I could change this in just the wordpress plugin but I would like to keep the changes between the wordpress plugin and the original RRSSB project to a minimum. Also, this change may help others avoid problems when integrating RRSSB directly into their sites or when using one of the other third-party versions. 
- aarreedd

**Comment by stevenmusumeche** [comment]
This broke backwards-compatibility with version 1.6.0, seems like a minor version release shouldn't do that.
