### ISSUE TITLE
class="popup" doesn't trigger a popup - can't figure out where the conflict is

### ISSUE THREAD

**Issue by jmedwards** [kni-labs/rrssb#50]
Thank you for everyone who has contributed to RRSSB - the buttons are awesome! I just wish I could get the popup to work.

http://www.kayako.com/company/careers/26376

**Comment by daninfpj** [comment]
What about when you insert the buttons in the DOM after the document has initialised? For example when you render a Backbone template. Shouldn't you be allowed to initialise the plugin, including event listeners and rrssbInit, with a function call?

Just like carrot/share-button:
`var share = new Share(".share-button");`

**Comment by patroqueeet** [comment]
@daninfpj  +1
