### ISSUE TITLE
WordPress Version Suddenly Disappeared

### ISSUE THREAD

**Issue by espellcaste** [kni-labs/rrssb#63]
Anyone knows why the WP version disappeared from the WP Plugins Repository?!

**Comment by nerdworker** [comment]
@alan-reed Any news about the WordPress plugin version? It's still not listed in the repo.

**Comment by aarreedd** [comment]
Sorry, I have not had time to work on this. The plugin is on my github but
not the WP repository.

On Wed, Jun 10, 2015 at 3:38 PM, nerdworker.com <notifications@github.com>
wrote:

> @alan-reed <https://github.com/alan-reed> Any news about the WordPress
> plugin version? It's still not listed in the repo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kni-labs/rrssb/issues/63#issuecomment-110887926>.
>



-- 
_________
Alan Reed

pub: https://pgp.mit.edu/pks/lookup?op=get&search=0x883581C543909213
<http://pgp.mit.edu/pks/lookup?op=get&search=0x883581C543909213>
