### ISSUE TITLE
WP License Issue

### ISSUE THREAD

**Issue by alan-reed** [kni-labs/rrssb#64]
rrssb is licensed "Creative Commons Attribution-ShareAlike 4.0 International license". Wordpress requires a GPL-Compatible license for all plugins in their repository. As a result, WP removed the rrssb plugin. Can rrssb's license change to be GPL-Compatible?

**Comment by dbox** [comment]
@joshuatuscan I can't remember where we landed on this one...

**Comment by dbox** [comment]
@b2z So what are you recommending we use? We just don't want people to be able to release RRSSB as a paid plugin by itself. Totally fine for you to build into templates or w/e.

**Comment by dbox** [comment]
@alan-reed @b2z Switched to MIT License

**Comment by fbm-static** [comment]
Hello, @alan-reed I hope you can bring the plugin back to da wordpress directory.

**Comment by alan-reed** [comment]
Thank you to kni-labs for changing the license. I need to update the
Wordpress plugin with the latest RRSSB code and then resubmit it to
Wordpress. Hopefully I will have a chance to work on it sometime soon.

On Tue, Apr 21, 2015 at 7:27 PM, Xof Nagem <notifications@github.com> wrote:

> Hello, @alan-reed <https://github.com/alan-reed> I hope you can bring the
> plugin back to da wordpress directory.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kni-labs/rrssb/issues/64#issuecomment-94972786>.
>



-- 
_________
Alan Reed

pub: https://pgp.mit.edu/pks/lookup?op=get&search=0x883581C543909213
<http://pgp.mit.edu/pks/lookup?op=get&search=0x883581C543909213>

**Comment by fbm-static** [comment]
Thank you @alan-reed Good day!

**Comment by fbm-static** [comment]
:sparkles:
