### ISSUE TITLE
Facebook Share shows 500 Internal Error

### ISSUE THREAD

**Issue by jackpilowsky** [kni-labs/rrssb#65]
I'm working on a site that doesn't have an SSL. 

The URL is dynamically populated. When I add https to the URL, it displays the correct info(but the link back to the site doesn't work because HTTPS is not available on the server). When I switch it back, I get the 500 internal error again.

**Comment by aicarlson** [comment]
Is the URL properly encoded? Your site doesn't need to have an SSL in order to get the Facebook popup to work.
