### ISSUE TITLE
Possible to pass title, body and subreddit into the reddit share?

### ISSUE THREAD

**Issue by deronsizemore** [kni-labs/rrssb#68]
I'd like to be able to pass that info into the submit page when someone shares on reddit.

Thanks

**Comment by aicarlson** [comment]
As far as I can tell you can't pass the subreddit through a Reddit share because Reddit validates the subreddit before the submission process. I'll write something for passing the title and text later today.

**Comment by dbox** [comment]
Thats up

**Comment by deronsizemore** [comment]
Thank you!

**Comment by deronsizemore** [comment]
Thanks again for this. I'm finally getting around to messing with this. I noticed that I mistyped my question initially. When sharing a link on Reddit, it doesn't really make sense to share a "body" as at that point, you're no longer sharing a link and it becomes a self post. Is there a way to pass in a URL in the reddit share button? Also, regarding passing the subreddit, I noticed on their api page: http://www.reddit.com/dev/api#POST_api_submit they have a way to pass the subreddit. I was wondering if this would allow you to add this functionality?

Thanks

**Comment by AdamPS** [comment]
So if we can't have both text and url (and we should test this I guess), it looks like there is an action to remove the text parameter from both V1 and V2.  Also, in that latest API, the URL is slightly different ("/api/submit") and it suggests there should be a kind parameter.  I don't have an account to test.

Regarding subreddit - it would be easy to pass it, but how to decide what value to pass?  In index.html is could only be an example.

**Comment by deronsizemore** [comment]
Sorry for my delayed response here.

>it suggests there should be a kind parameter. I don't have an account to test.

What is a "kind parameter?" Also, I have an account and can test things if you needed me to?

>Regarding subreddit - it would be easy to pass it, but how to decide what value to pass?

I assume it would just be hard coded? For me, I'd need to only every submit to a single subreddit which will never change.
