### ISSUE TITLE
Not rendering correctly with multiple instances

### ISSUE THREAD

**Issue by simonv4549** [kni-labs/rrssb#75]
I came across an issue where on mobile the button text would wrap, I thought it may have been something that I had done by mistake while I was customizing so I thought I would revert everything back to your code from the demo page. But the issue still exists, and the strange thing is if I add a 2nd instance of your code the 1st instance then works perfect. If I add 3 or 4 instances the first X works fine only the final instance is wrapping the text?

I have created a demo page here on my site so you can see what I mean, If you view this on mobile (iphone5 I was using) or even in Chrome with mobile emulation you will see the issue? 
http://www.certforums.com/pages/rrssb/
![rrssb](https://cloud.githubusercontent.com/assets/8165138/5771182/8a0069c8-9d6a-11e4-9768-e1a52d43a9e9.png)

Could you help with a fix?

**Comment by simonv4549** [comment]
Does anyone still maintain this script? I found the text wrapping issue as it was a CSS conflict with word-wrap used in the template. 

But I still have the issue where if more than one instance is shown the last instance does not render the same as the other instance. Does anyone else have this issue? At certain screen widths the last instance the buttons change size at different intervals.

**Comment by dbox** [comment]
I looked at your page. Seems to be all good?

**Comment by simonv4549** [comment]
This is still an issue, Please can you look into it further.

If you view the page http://www.certforums.com/pages/rrssb/ at certain resolutions you will see the issue I have added 3 instances so you can see its always the final instance that it happens. 

Use google chrome with mobile inspector and use Google Nexus 4 as the device and you will see the issue.

![screen](https://cloud.githubusercontent.com/assets/8165138/5889676/1252b2de-a466-11e4-9868-de2c57da9b4d.png)

**Comment by dbox** [comment]
@simonv4549 i can't replicate it on the example you provided

**Comment by simonv4549** [comment]
Well Im at a loss has to how you cant see this and I have multiple confirmations from others that it happens. I happens even within the browser when resized and I checked with the latest version of FF and Chrome on Mac and IE11 and FF on Windows and I can see it by resizing the window to a narrow viewpoint. Plus using the Chrome Mobile Emulation everyone I have asked to test it can see it happening. I also have somebody viewing from a LG 4 phone who first pointed this out to me that 100% can see this issue.

I really dont know what more I can do to try to explain it to you, do you have any ideas?

**Comment by tmaiaroto** [comment]
I see the same thing. The first share button, regardless of which one it is, does not size properly. It includes the text when it shouldn't.

**Comment by dbox** [comment]
@tmaiaroto Have a chance to look into this?

**Comment by dbox** [comment]
//cc @aicarlson

**Comment by aicarlson** [comment]
This weekend is tight, but I'll look into it further as soon as I can.

**Comment by dbox** [comment]
Np. Thanks!

**Comment by dbox** [comment]
Ideally would love to get this guy fixed before 2.0, so that the last version of 1.x.x is super stable as well.

**Comment by connorwyatt** [comment]
I see, I can't replicate this issue, might have another look at some point

**Comment by dbox** [comment]
I never could either. @tmaiaroto or @simonv4549 can you put your test page back up and we'll give it another look. thanks!

**Comment by connorwyatt** [comment]
Yeah that would help

**Comment by aicarlson** [comment]
Sorry guys, I fully intended to look into this further since I was able to replicate but I've just been slammed with work recently.

**Comment by dbox** [comment]
:iknowthatfeel:

**Comment by connorwyatt** [comment]
Could you replicate the issue?

**Comment by dbox** [comment]
@aicarlson could, yes

**Comment by aicarlson** [comment]
Alright, I don't have time to debug right now but the least I could do is set it up in an instance where this is an issue.

http://codepen.io/aicarlson/full/EjgvzW/

Chrome 43.0.2357.65 (64-bit) (This is what I'm in now, it happens in more browsers)
Mac OSX Yosemite

Reduce the screen size to ~400px and you'll see that the last row of icons resizes differently than the preceding 3 rows.

**Comment by dbox** [comment]
Thanks @aicarlson

**Comment by aicarlson** [comment]
It's the least I can do, sorry I can't be of more help! If you aren't able to replicate it on there let me know.

Date: Thu, 21 May 2015 08:41:46 -0700

**Comment by dbox** [comment]
I'm seeing it there.

**Comment by connorwyatt** [comment]
Right I see too. This will need sorting as it will still be present in 2.0 otherwise

**Comment by connorwyatt** [comment]
I'll take a look in a bit

**Comment by connorwyatt** [comment]
Me too

**Comment by dbox** [comment]
@joshuatuscan Any ideas on this guy? (See @aicarlson's code pen a few posts up)

**Comment by connorwyatt** [comment]
I might be able to find out what is wrong as im building 2.0 up incrementally, at the moment I have no idea though

**Comment by dbox** [comment]
@aicarlson Do you still have that codepen somewhere? Link is 404ing for me.

**Comment by aicarlson** [comment]
I don't, I think I cleaned it out a little while back. I could replicate it
for you again, I'll try to get that to you guys today.

**Comment by dbox** [comment]
@aicarlson No worries. I just did it.

This is definitely still happening. Currently happening in Chrome, but not Safari or Firefox for me:

http://codepen.io/dbox/full/vLONzd/

**Comment by oskar9** [comment]
In my case this is happiness not in the first loop but other loops in Chrome just for Icons not button, but if I change the browser size smaller enough the button disappeared and now it shows the icons.
![social](https://cloud.githubusercontent.com/assets/5046473/12392039/3990d3a8-bdec-11e5-8126-f72b7430fd44.JPG)

**Comment by oskar9** [comment]
So, Is there an option to turn off the button and only show the icon?

**Comment by dbox** [comment]
@oskar9 it does that automatically below a certain size ...
![image](https://cloud.githubusercontent.com/assets/296130/12394148/b934dd02-bdbf-11e5-9d74-80c5310e8cff.png)

I've never seen that issue. Feel free to hop in chat to help debug your specific case: https://gitter.im/kni-labs/rrssb?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

Multiple instances per page weren't part of the original scope of the project, but we'll keep trying to get it working.

**Comment by oskar9** [comment]
![Uploading share2.JPG…]()

**Comment by aicarlson** [comment]
I'm poking around at this again in my 'spare' time. I thought it might have something to do with the debounce function but that was a false positive.

**Comment by dbox** [comment]
Spare time? What's that!

**Comment by aicarlson** [comment]
@dbox Good question, I'll let you know when I find out!

**Comment by dbox** [comment]
:) Thanks for poking around again!

**Comment by dbox** [comment]
Anyone have any new insight on this? Multiple instances weren't really part of the initial plan for this repo, so going to close this for now. If anyone is able to get a fix going please submit a PR. Thanks!
