### ISSUE TITLE
Not rendering correclty

### ISSUE THREAD

**Issue by simonv4549** [kni-labs/rrssb#79]
Hey, you closed my issue without fully looking into it, can you please take a further look: https://github.com/kni-labs/rrssb/issues/75

**Comment by aicarlson** [comment]
I was able to replicate this as well. If you have multiple identical instances of RRSSB on a single page with the same number of buttons each (there must be enough buttons to trigger the small layout - eg: 7 buttons), the last instance will not catch the small layout and will keep the square buttons with the exception of the first button, which stays wide. 

I haven't resolved the issue yet, but I was able to replicate in Chrome on Yosemite.

**Comment by simonv4549** [comment]
Thank you, Im still stuck with this issue and have no fix either. The developer says he cannot replicate it and closed my previously opened issue as a non issue but the more people that can report it the more chance of it being looked at further. 

Further information on the issue in the issue can be found here: https://github.com/kni-labs/rrssb/issues/75

**Comment by dbox** [comment]
Sorry for closing. If @aicarlson was able to replicate, then it must be legit!

**Comment by dbox** [comment]
@aicarlson Is this still an issue?

**Comment by simonv4549** [comment]
Yes its still an issue as aicarlson and I described here and also tmaiaroto in https://github.com/kni-labs/rrssb/issues/75.
