### ISSUE TITLE
Dropbox links to examples missing

### ISSUE THREAD

**Issue by peschee** [kni-labs/rrssb#83]
Hi

The two files linking to the min and max versions (as screenshots) seem to be missing:

- https://www.dropbox.com/s/2k6lcebg2887ge3/Screenshot%202014-02-18%2009.45.45.png
- https://www.dropbox.com/s/1juq03011lixk3r/Screenshot%202014-02-18%2009.43.57.png

**Comment by dbox** [comment]
fixed one of them. No idea where the other one went. Removed link.
