### ISSUE TITLE
Vote: Grunt / Gulp

### ISSUE THREAD

**Issue by dbox** [kni-labs/rrssb#92]
Back when we set this up, we were using Codekit to compile Sass, but I personally haven't used it for any other projects for over a year now. 

Thinking we should probably set up Grunt or Gulp. I've used Gulp a bit, but happy to do whichever the group prefers.

**Comment by aicarlson** [comment]
I have more experience with Grunt, but I'm open.

**Comment by connorwyatt** [comment]
Gulp generally runs quicker than grunt ;)

**Comment by dbox** [comment]
Would anyone be up for setting up a simple browsersync / sass compiling gulp file so we can kick codekit to the curb? @aicarlson @connorwyatt 

http://www.browsersync.io/docs/gulp/#gulp-sass-css this looks pretty good....

Ideally I'd like to start with it in  its own branch ie  `gulp` and not the `dev` branch

I imagine we'll need to do some folder structure modification too.

**Comment by connorwyatt** [comment]
I can give you a gulp config file that you could modify, it runs real quick and I use SCSS, browsersync (as well as jade and other stuff) and it also watches for file changes and compiles the files when necessary.

I actually moved from codekit to grunt and then quickly onto gulp so I know the feeling :)

**Comment by connorwyatt** [comment]
I've just started working on the gulp config, I'll keep you informed and create a pull request when I'm done

**Comment by connorwyatt** [comment]
Completed, and I've added a PR. Let me know if you think something needs changing.

**Comment by QWp6t** [comment]
Gulp is undeniably better. There is no reason to use grunt anymore. This wasn't the case a year or two ago when gulp was still new, but at this point gulp has all the same offerings as grunt.

You can feel free to use the [gulpfile.js from Sage](https://github.com/roots/sage/blob/master/gulpfile.js) if you'd like. Although the project is a WordPress theme, there is nothing WordPress-specific about our gulp file.

**Comment by dbox** [comment]
Thanks @QWp6t. I just merged @connorwyatt 's gulp setup up. I wont be able to merge into master until tonight but feel free to check it out from `dev` branch.

**Comment by dbox** [comment]
Gulp it is! Thanks again @connorwyatt . I think we may want to change our directory structure in the future to have `assets` and `dist` folders, but I'll start a new thread for that.

**Comment by connorwyatt** [comment]
You’re welcome, and that shouldn’t take much work, the gulp file is quite straight forward and would only require a rewrite of filenames and destinations.

If I get some time I’ll have a look at it but I’d need to know what you plan is for organisation :)
