### ISSUE TITLE
What happened to the wordpress plugin?

### ISSUE THREAD

**Issue by fbm-static** [kni-labs/rrssb#93]
It got deleted.

**Comment by QWp6t** [comment]
It should hopefully be back soon, now that the code uses MIT license.

But to answer your question: https://github.com/kni-labs/rrssb/issues/64

**Comment by dbox** [comment]
Ping!

**Comment by jsmoriss** [comment]
FYI - I'm working on an RRSSB extension for WPSSO. It should be available shortly. ;-)

**Comment by dbox** [comment]
Nice! Keep us posted

**Comment by dbox** [comment]
https://wordpress.org/plugins/wpsso-rrssb/

@jsmoriss has released a WP plugin. Please direct all wp-related questions there! Thanks!
